"""Authoritative Pydantic models for Milestone 3 dataset contracts."""

from .character_class import (
    CharacterClass,
    ClassFeature,
    ClassProgression,
    HitDie,
    ProgressionColumn,
    ProgressionLevel,
    Subclass,
    SubclassFeature,
)
from .common import (
    AdditionalSection,
    DatasetId,
    EntryBase,
    EntryReference,
    ImageReference,
    LocalKey,
    SourceKey,
    SourceMetadata,
    StableReference,
    display_edition,
    split_reference,
)
from .dataset import (
    DATASET_SCHEMA_VERSION,
    DatasetDependency,
    DatasetManifest,
    DatasetPack,
    DatasetValidationError,
    validate_dataset,
)
from .feat import Feat
from .glossary import GlossaryEntry
from .item import (
    ArmorDetails,
    Item,
    ItemCatalog,
    ItemCost,
    ItemKind,
    ItemProperty,
    ItemPropertyReference,
    ItemRarity,
    WeaponDetails,
)
from .monster import Monster, MonsterAbility, cr_value
from .spell import MagicSchool, Spell, SpellComponents

__all__ = [
    "AdditionalSection",
    "ArmorDetails",
    "CharacterClass",
    "ClassFeature",
    "ClassProgression",
    "DATASET_SCHEMA_VERSION",
    "DatasetDependency",
    "DatasetId",
    "DatasetManifest",
    "DatasetPack",
    "DatasetValidationError",
    "EntryBase",
    "EntryReference",
    "Feat",
    "GlossaryEntry",
    "HitDie",
    "ImageReference",
    "Item",
    "ItemCatalog",
    "ItemCost",
    "ItemKind",
    "ItemProperty",
    "ItemPropertyReference",
    "ItemRarity",
    "LocalKey",
    "MagicSchool",
    "Monster",
    "MonsterAbility",
    "ProgressionColumn",
    "ProgressionLevel",
    "SourceKey",
    "SourceMetadata",
    "Spell",
    "SpellComponents",
    "StableReference",
    "Subclass",
    "SubclassFeature",
    "WeaponDetails",
    "display_edition",
    "cr_value",
    "split_reference",
    "validate_dataset",
]
